# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: cassetteos-message-bus
before:
  hooks:
    - rm -rf third_party_licenses
    - go generate
    - go run github.com/google/go-licenses@latest check . --disallowed_types=restricted
    - bash -c 'go run github.com/google/go-licenses@latest save . --save_path=third_party_licenses || true'
    - bash -c 'cp -r license_overrides/* third_party_licenses/ || true'
    - go mod tidy
    - go test -race -v ./...
builds:
  - id: cassetteos-message-bus-amd64
    binary: build/sysroot/usr/bin/cassetteos-message-bus
    env:
      - CC=x86_64-linux-gnu-gcc
    gcflags:
      - all=-N -l
    ldflags:
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.Version={{.Version}} 
      - -extldflags "-static"
    tags:
      - musl
      - netgo
      - osusergo
    goos:
      - linux
    goarch:
      - amd64
  - id: cassetteos-message-bus-arm64
    binary: build/sysroot/usr/bin/cassetteos-message-bus
    env:
      - CC=aarch64-linux-gnu-gcc
    gcflags:
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.Version={{.Version}} 
      - all=-N -l
    ldflags:
      - -extldflags "-static"
    tags:
      - musl
      - netgo
      - osusergo
    goos:
      - linux
    goarch:
      - arm64
  - id: cassetteos-message-bus-arm-7
    binary: build/sysroot/usr/bin/cassetteos-message-bus
    env:
      - CC=arm-linux-gnueabihf-gcc
    gcflags:
      - all=-N -l
    ldflags:
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.Version={{.Version}} 
      - -extldflags "-static"
    tags:
      - musl
      - netgo
      - osusergo
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - "7"
  - id: cassetteos-message-bus-migration-tool-amd64
    binary: build/sysroot/usr/bin/cassetteos-message-bus-migration-tool
    main: ./cmd/migration-tool
    env:
      - CC=x86_64-linux-gnu-gcc
    gcflags:
      - all=-N -l
    ldflags:
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.Version={{.Version}} 
      - -extldflags "-static"
    tags:
      - musl
      - netgo
      - osusergo
    goos:
      - linux
    goarch:
      - amd64
  - id: cassetteos-message-bus-migration-tool-arm64
    binary: build/sysroot/usr/bin/cassetteos-message-bus-migration-tool
    main: ./cmd/migration-tool
    env:
      - CC=aarch64-linux-gnu-gcc
    gcflags:
      - all=-N -l
    ldflags:
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.Version={{.Version}} 
      - -extldflags "-static"
    tags:
      - musl
      - netgo
      - osusergo
    goos:
      - linux
    goarch:
      - arm64
  - id: cassetteos-message-bus-migration-tool-arm-7
    binary: build/sysroot/usr/bin/cassetteos-message-bus-migration-tool
    main: ./cmd/migration-tool
    env:
      - CC=arm-linux-gnueabihf-gcc
    gcflags:
      - all=-N -l
    ldflags:
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.Version={{.Version}} 
      - -extldflags "-static"
    tags:
      - musl
      - netgo
      - osusergo
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - "7"
archives:
  - name_template: >-
      {{ .Os }}-{{- if eq .Arch "arm" }}arm-7{{- else }}{{ .Arch }}{{- end }}-{{ .ProjectName }}-v{{ .Version }}
    id: cassetteos-message-bus
    builds:
      - cassetteos-message-bus-amd64
      - cassetteos-message-bus-arm64
      - cassetteos-message-bus-arm-7
    files:
      - build/**/*
      - third_party_licenses
  - name_template: >-
      {{ .Os }}-{{- if eq .Arch "arm" }}arm-7{{- else }}{{ .Arch }}{{- end }}-{{ .ProjectName }}-migration-tool-v{{ .Version }}
    id: cassetteos-message-bus-migration-tool
    builds:
      - cassetteos-message-bus-migration-tool-amd64
      - cassetteos-message-bus-migration-tool-arm64
      - cassetteos-message-bus-migration-tool-arm-7
    files:
      - build/sysroot/etc/**/*
      - third_party_licenses
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-snapshot"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  github:
    owner: BeesNestInc
    name: CassetteOS-MessageBus
  draft: true
  prerelease: auto
  mode: replace
  name_template: "v{{ .Version }}"
